font_family      FantasqueSansM Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 13.0

disable_ligatures no
enable_audio_bell no

shell fish
# shell_integration disabled
# shell_integration no-cursor
url_style curly
remember_window_size no

initial_window_height 480
initial_window_width 640
cursor_shape block
cursor_blink_interval 0
window_padding_width 10

#background #0c1115
#foreground #ffffff
#cursor #6c6c6c
#selection_background #bd2523
#selection_foreground #0c1115

background_opacity 0.90
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0

confirm_os_window_close 0

sync_to_monitor no

# colors

# vim:ft=kitty

## name: srcery
## author: Daniel Berg
## license: MIT
## upstream: https://github.com/srcery-colors/srcery-terminal/blob/master/kitty/srcery_kitty.conf
## blurb: Srcery is a color scheme with clearly defined contrasting colors and
## a slightly earthy tone.

#: The basic colors

foreground                      #fce8c3
background                      #1c1b19
selection_foreground            #1c1b19
selection_background            #fce8c3


#: Cursor colors

cursor                          #fbb829
cursor_text_color               background


#: The basic 16 colors

#: black
color0 #1c1b19
color8 #918175

#: red
color1 #ef2f27
color9 #f75341

#: green
color2  #519f50
color10 #98bc37

#: yellow
color3  #fbb829
color11 #fed06e

#: blue
color4  #2c78bf
color12 #68a8e4

#: magenta
color5  #e02c6d
color13 #ff5c8f

#: cyan
color6  #0aaeb3
color14 #2be4d0

#: white
color7  #baa67f
color15 #fce8c3

# START_AUTOGENERATED_TAB_STYLE
# Feel free to update these colors manually and remove these comments.
active_tab_foreground   #444444
active_tab_background   #fce8c3
inactive_tab_foreground #fce8c3
inactive_tab_background #161614
# END_AUTOGENERATED_TAB_STYLE
